# Generated by Django 5.2 on 2025-05-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_candidate_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyresponsibilities',
            old_name='key_responsibility',
            new_name='key_responsibilities',
        ),
    ]
