# Generated by Django 5.2 on 2025-05-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_candidate_address_candidate_address_cont_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.candidate'),
            preserve_default=False,
        ),
    ]
