# Generated by Django 5.2 on 2025-05-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_education_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_data',
            field=models.DateField(default="2020-12-20"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address_cont',
            field=models.TextField(blank=True, null=True),
        ),
    ]
