# Generated by Django 5.2 on 2025-05-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_education_start_data_alter_candidate_address_cont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
