# Generated by Django 5.2 on 2025-05-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_start_data_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
