# Generated by Django 5.2 on 2025-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeID', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='resume')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job_role', models.CharField(max_length=50)),
            ],
        ),
    ]
