# Generated by Django 5.2 on 2025-05-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
