# Generated by Django 5.2 on 2025-05-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_templates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
    ]
